### ISSUE TITLE
storing configurations in different config name files and include in the main config file

### ISSUE THREAD

**Issue by hbakhtiyor** [pleerock/configuration-manager#1]
it would be nice to add the feature which we can store each specific configuration to own config file and include to main config file.

**Comment by pleerock** [comment]
actually it is [there](https://github.com/pleerock/configuration-manager#using-multiple-configuration-files) already, but I think you have to upgrade to latest versions of all libraries including microframework and all its dependencies

**Comment by hbakhtiyor** [comment]
nice
